version: '3'
services: 
  postgres-db: 
    container_name: postgres-db-new
    image: 'postgres:latest'
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-db-data:/var/lib/postgresql/data

volumes:
    postgres-db-data:
        name: postgres-db-data         
 
