version: '3'
services: 
  postgres-db: 
    container_name: postgres-db-new
    image: 'postgres:latest'
    ports:
      - '000:5432'
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    volumes:
      - postgres-db-data:/var/lib/postgresql/data

volumes:
    postgres-db-data:
        name: postgres-db-data         
 
